### ISSUE TITLE
[A-08]: 원하는 위치를 사진 및 동영상의 마커로 설정할 수 있다.

### ISSUE THREAD

**Issue by wsb7788** [boostcampwm2023/and01-SnapPoint#15]
## 작업 내용

- [x] 마커 움직이기
- [x] 마커로부터 위치 정보 가져오기

## 참고한 자료
- 지도 추가
https://developers.google.com/maps/documentation/android-sdk/map?hl=ko#maps_android_map_fragment-kotlin
- 마커 드래그 이벤트
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMarkerDragListener

## 스크린샷 (필수)

![GIFS2](https://github.com/boostcampwm2023/and01-SnapPoint/assets/76683420/d0c9cb4a-d4ce-4b5c-8122-e948b3e4a1cd)

**Comment by rbybound** [comment]
## 추가개선
- 실제 마커를 만드는 것이 아닌 가상의 마커를 화면 중앙에 그리고, 중앙의 위치만 가져온다.
- 마커 디자인이 나와야 하기 때문에 사진 추가 기능 이후에 개선한다.
